using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Aeon.Emulator.DebugSupport;
using Aeon.Emulator.Launcher.Debugger;

namespace Aeon.Emulator.Launcher
{
    public sealed partial class DebuggerWindow : Window
    {
        public static readonly StyledProperty<EmulatorHost?> EmulatorHostProperty = 
            AvaloniaProperty.Register<DebuggerWindow, EmulatorHost?>(nameof(EmulatorHost));
        public static readonly StyledProperty<bool> IsHexFormatProperty = 
            AeonDebug.IsHexFormatProperty.AddOwner<DebuggerWindow>();
        public static readonly StyledProperty<InstructionLog?> InstructionLogProperty = 
            AvaloniaProperty.Register<DebuggerWindow, InstructionLog?>(nameof(InstructionLog));

        private Disassembler? disassembler;

        public DebuggerWindow()
        {
            InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            disassemblyView = this.FindControl<DisassemblyView>("disassemblyView")!;
            registerView = this.FindControl<RegisterViewer>("registerView")!;
            memoryView = this.FindControl<MemoryView>("memoryView")!;
        }

        // Fields generated by Avalonia

        public EmulatorHost? EmulatorHost
        {
            get => GetValue(EmulatorHostProperty);
            set => SetValue(EmulatorHostProperty, value);
        }
        
        public bool IsHexFormat
        {
            get => GetValue(IsHexFormatProperty);
            set => SetValue(IsHexFormatProperty, value);
        }
        
        public InstructionLog? InstructionLog
        {
            get => GetValue(InstructionLogProperty);
            set => SetValue(InstructionLogProperty, value);
        }

        public void UpdateDebugger()
        {
            if (EmulatorHost == null) return;
            
            var vm = EmulatorHost.VirtualMachine;

            disassembler = new Disassembler(EmulatorHost.VirtualMachine)
            {
                StartSegment = vm.Processor.CS,
                StartOffset = vm.Processor.EIP,
                MaximumInstructions = 1000
            };

            var disasm = disassembler.Instructions;
            disassemblyView.InstructionsSource = disasm;
            registerView.RegisterSource = vm.Processor;
            memoryView.MemorySource = vm.PhysicalMemory;
        }
    }
}
